### ISSUE TITLE
Issue with ABOD

### ISSUE THREAD

**Issue by e101sg** [stratosphereips/zeek_anomaly_detector#6]
Hi, 

Thanks for wonderful tool. I am beginner here. I am trying to run the anomaly detection run in a  Debian Honeypot setup. No issues with installation. Zeek also installed and running inside Honeypot environment. When run script with default  the PCA algorithm, no issue.
when `clf = ABOD()` getting following error. 

Hope it is not related to Python version. Honey pot running on **Python 3.9.2** . Any thoughts will be highly useful. 
Thanks! Cheers! 

![Anomaly_detection_abod](https://user-images.githubusercontent.com/1925934/221554696-cb97fb93-36dd-4e69-8076-a028edf7f158.png)

**Comment by eldraco** [comment]
Hi @e101sg . Thanks for the issue.
We never tried ABOD(), so I'm not sure what the method needs. 
check the documentation for ABOD and see what values it requires. Our tool uses floats for all the numeric features. 
Maybe that is not compatible?

**Comment by e101sg** [comment]
okay. Noted with Thanks.
